Origin/artigo introducao
2023M6T1-Inteli/grupo3 pull request #39
Opened 2023-05-11 20:37 UTC by Rafael-Cabral

2023-05-13 14:24 UTC, dtonavitor requested changes

2023-05-13 14:24 UTC, dtonavitor commented on artigo/artigo.md
> +A indústria de papel e a conversão de produtos de papel tem uma porção muito significativa na economia global. A otimização de processos, como o corte de papel, torna-se relevante ao observarmos que
A palavra "papel" está com algumas repetições. Seria bom tentar evitá-las.

2023-05-13 14:24 UTC, dtonavitor commented on artigo/artigo.md
> +MILNITZ, Diego; MENDES LUNA, Monica Maria. **Alocação física de produtos em transportadoras por meio da aplicação da ferramenta de programação linear em uma empresa do setor têxtil**. Exacta, São Pau
A ordem das referências deve ser em ordem alfabética

2023-05-14 07:51 UTC, melyssa08 requested changes
Minhas observações são as mesmas do Vitor

2023-05-15 00:54 UTC, Rafael-Cabral reviewed
Feito!

2023-05-15 01:04 UTC, melyssa08 approved these changes

2023-05-15 01:09 UTC, dtonavitor approved these changes

2023-05-15 01:39 UTC, merged